import 'package:flutter/material.dart';
import '../models/subject.dart';
import '../services/supabase_service.dart';
import '../utils/grade_utils.dart';

class CGPAProvider extends ChangeNotifier {
  final SupabaseService _service = SupabaseService();

  List<Subject> _subjects = [];
  bool _isLoading = false;
  String? _error;

  List<Subject> get subjects => _subjects;
  bool get isLoading => _isLoading;
  String? get error => _error;

  double get cgpa => GradeUtils.calculateCGPA(_subjects);

  // Group subjects by semester for SGPA display
  Map<int, List<Subject>> get bySemester {
    final map = <int, List<Subject>>{};
    for (final s in _subjects) {
      map.putIfAbsent(s.semester, () => []).add(s);
    }
    return map;
  }

  double sgpaForSemester(int semester) {
    final list = _subjects.where((s) => s.semester == semester).toList();
    return GradeUtils.calculateCGPA(list);
  }

  Future<void> loadSubjects(String userId) async {
    _isLoading = true;
    notifyListeners();

    try {
      _subjects = await _service.getSubjects(userId);
      _error = null;
    } catch (e) {
      _error = 'Failed to load subjects';
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> addSubject({
    required String userId,
    required String name,
    required double credits,
    required double gradePoint,
    required int semester,
  }) async {
    final subject = Subject(
      id: '', // generated by Supabase
      name: name,
      credits: credits,
      gradePoint: gradePoint,
      semester: semester,
    );
    await _service.addSubject(subject, userId);
    await loadSubjects(userId);
  }

  Future<void> deleteSubject(String id, String userId) async {
    await _service.deleteSubject(id);
    await loadSubjects(userId);
  }
}
